//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSHExporter.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSHExporter.Resources.Localization.Resources.de", typeof(Resources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptieren.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken, um den Export abzubrechen.
        /// </summary>
        public static string CancelExport {
            get {
                return ResourceManager.GetString("CancelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablehnen.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten! Da du der Verwendung von Sentry nicht zugestimmt hast, kann dein Feedback leider nicht erfasst werden..
        /// </summary>
        public static string ErrorGenericNoSentry {
            get {
                return ResourceManager.GetString("ErrorGenericNoSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentry wird verwendet, um dein Feedback zu senden. Da du der Verwendung von Sentry nicht zugestimmt hast, kann dein Feedback leider nicht erfasst werden..
        /// </summary>
        public static string ErrorNoSentry {
            get {
                return ResourceManager.GetString("ErrorNoSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du den Export abbrechen?.
        /// </summary>
        public static string ExportCancelExport {
            get {
                return ResourceManager.GetString("ExportCancelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Ordner:.
        /// </summary>
        public static string ExportChosenFolder {
            get {
                return ResourceManager.GetString("ExportChosenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Export:.
        /// </summary>
        public static string ExportExport {
            get {
                return ResourceManager.GetString("ExportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Export wurde abgebrochen. Manche Dateien wurden möglichbereits bereits exportiert..
        /// </summary>
        public static string ExportExportCancelled {
            get {
                return ResourceManager.GetString("ExportExportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Datei wurde erfolgreich exportiert!.
        /// </summary>
        public static string ExportFileExported {
            get {
                return ResourceManager.GetString("ExportFileExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Dateien wurden erfolgreich exportiert!.
        /// </summary>
        public static string ExportFilesExported {
            get {
                return ResourceManager.GetString("ExportFilesExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Ordner.
        /// </summary>
        public static string ExportFolder {
            get {
                return ResourceManager.GetString("ExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Ordner enthält bereits Dateien. Dateien werden überschrieben, wenn sie denselben Namen haben. Bist du sicher, dass du diesen Ordner verwenden möchtest?.
        /// </summary>
        public static string ExportFolderContainsFiles {
            get {
                return ResourceManager.GetString("ExportFolderContainsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Dateiformat:.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle mindestens ein Export-Dateiformat aus!.
        /// </summary>
        public static string ExportMissingFileFormat {
            get {
                return ResourceManager.GetString("ExportMissingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle zuerst einen Export-Ordner aus!.
        /// </summary>
        public static string ExportMissingFolder {
            get {
                return ResourceManager.GetString("ExportMissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Export-Optionen:.
        /// </summary>
        public static string ExportOtherOptions {
            get {
                return ResourceManager.GetString("ExportOtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Ausgewählte Gruppen und Beiträge:.
        /// </summary>
        public static string ExportSelected {
            get {
                return ResourceManager.GetString("ExportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Text-Optionen:.
        /// </summary>
        public static string ExportTextOptions {
            get {
                return ResourceManager.GetString("ExportTextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Feedback wird an Maxi gesendet! Du kannst z.B. auch Links zu Bildern einfügen..
        /// </summary>
        public static string FeedbackDetailsDefault {
            get {
                return ResourceManager.GetString("FeedbackDetailsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etwas ist unerwartet schief gelaufen! Der Fehler wurde mit der ID {0} registriert..
        /// </summary>
        public static string FeedbackDetailsError {
            get {
                return ResourceManager.GetString("FeedbackDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du möglicherweise kontaktiert werden möchtest, gib hier deine E-Mail-Adresse ein:.
        /// </summary>
        public static string FeedbackEmailDefault {
            get {
                return ResourceManager.GetString("FeedbackEmailDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du per E-Mail benachrichtigt werden möchtest, wenn der Fehler behoben ist, gib deine E-Mail-Adresse hier ein:.
        /// </summary>
        public static string FeedbackEmailError {
            get {
                return ResourceManager.GetString("FeedbackEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib dein Feedback hier ein:.
        /// </summary>
        public static string FeedbackResponseDefault {
            get {
                return ResourceManager.GetString("FeedbackResponseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn möglich, gib hier bitte mehr Details darüber an, was du getan hast, bevor der Fehler aufgetreten ist:.
        /// </summary>
        public static string FeedbackResponseError {
            get {
                return ResourceManager.GetString("FeedbackResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke für dein Feedback!.
        /// </summary>
        public static string FeedbackTitleDefault {
            get {
                return ResourceManager.GetString("FeedbackTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten!.
        /// </summary>
        public static string FeedbackTitleError {
            get {
                return ResourceManager.GetString("FeedbackTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word-Datei (.docx) - Enthält Text und (wenn ausgewählt) Bilder.
        /// </summary>
        public static string FileFormatDocx {
            get {
                return ResourceManager.GetString("FileFormatDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML-Datei (.html) - Enthält formatierten Text und (wenn ausgewählt) Bilder.
        /// </summary>
        public static string FileFormatHtml {
            get {
                return ResourceManager.GetString("FileFormatHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-Datei (.txt) - Enthält nur Text, keine Formatierung und keine Bilder.
        /// </summary>
        public static string FileFormatTxt {
            get {
                return ResourceManager.GetString("FileFormatTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfe zunächst, ob du alle Gruppen und Beiträge ausgewählt hast, die du exportieren möchtest..
        /// </summary>
        public static string HelpExportStep1 {
            get {
                return ResourceManager.GetString("HelpExportStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst jederzeit zurückgehen, um Gruppen und Themen auszuwählen. Alle deine Änderungen werden automatisch gespeichert..
        /// </summary>
        public static string HelpExportStep2 {
            get {
                return ResourceManager.GetString("HelpExportStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginne den Exportvorgang, indem du den Ordner auswählst, in dem die Dateien gespeichert werden sollen. Dateien werden überschrieben, wenn sie bereits existieren..
        /// </summary>
        public static string HelpExportStep3 {
            get {
                return ResourceManager.GetString("HelpExportStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle dann das Format für die exportierten Dateien..
        /// </summary>
        public static string HelpExportStep4 {
            get {
                return ResourceManager.GetString("HelpExportStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lege fest, wie die Gruppen und Beiträge exportiert werden sollen..
        /// </summary>
        public static string HelpExportStep5 {
            get {
                return ResourceManager.GetString("HelpExportStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschließend kannst du den Export hier starten. (Der Export kann eine Weile dauern, besonders bei einer langsamen Internetverbindung.) Du kannst den Export jederzeit abbrechen, indem du auf die Ladeanimation klickst..
        /// </summary>
        public static string HelpExportStep6 {
            get {
                return ResourceManager.GetString("HelpExportStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib zuerst den Benutzernamen und das Passwort ein, die du bei Rollenspielhimmel verwendest, um dich einzuloggen..
        /// </summary>
        public static string HelpLoginStep1 {
            get {
                return ResourceManager.GetString("HelpLoginStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke dann hier, um dich einzuloggen und mit dem Auswählen deiner Gruppen und Beiträge fortzufahren..
        /// </summary>
        public static string HelpLoginStep2 {
            get {
                return ResourceManager.GetString("HelpLoginStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginne damit, die Gruppen auszuwählen. Wenn du auf eine Gruppe klickst, werden alle Beiträge dieser Gruppe geladen..
        /// </summary>
        public static string HelpSelectStep1 {
            get {
                return ResourceManager.GetString("HelpSelectStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle dann für jede Gruppe die Beiträge aus, die du exportieren möchtest..
        /// </summary>
        public static string HelpSelectStep2 {
            get {
                return ResourceManager.GetString("HelpSelectStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst hier alle Gruppen an- und abwählen....
        /// </summary>
        public static string HelpSelectStep3 {
            get {
                return ResourceManager.GetString("HelpSelectStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...und alle Beiträge hier..
        /// </summary>
        public static string HelpSelectStep4 {
            get {
                return ResourceManager.GetString("HelpSelectStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst eine Gruppe oder einen Beitrag im Browser öffnen, indem du auf das kleine Symbol rechts neben dem Namen der Gruppe oder des Beitrags klickst..
        /// </summary>
        public static string HelpSelectStep5 {
            get {
                return ResourceManager.GetString("HelpSelectStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du alle Gruppen und Beiträge ausgewählt hast, fahre mit dem Export fort, indem du hier klickst. (Du kannst auch wieder zurückgehen, ohne dass deine Änderungen verloren gehen.).
        /// </summary>
        public static string HelpSelectStep6 {
            get {
                return ResourceManager.GetString("HelpSelectStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schritt {0} von {1}.
        /// </summary>
        public static string HelpStep {
            get {
                return ResourceManager.GetString("HelpStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo! Diese Hilfedialoge helfen dir hoffentlich dabei, zu lernen, wie du dieses Programm benutzen kannst. Die meisten Seiten haben einen Hilfedialog, der erklärt, wie die aktuelle Seite funktioniert..
        /// </summary>
        public static string HelpWelcomeStep1 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du Sentry erlaubst, anonyme Daten zu sammeln, wenn ein Fehler auftritt, hilft mir das ungemein bei der Behebung dieser Fehler..
        /// </summary>
        public static string HelpWelcomeStep2 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst hier klicken, um zum Repository des Programms zu gelangen..
        /// </summary>
        public static string HelpWelcomeStep3 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du die aktuelle Versionsnummer des Programms sehen..
        /// </summary>
        public static string HelpWelcomeStep4 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Und hier das Team, das mir bei der Gestaltung und Programmierung hilft..
        /// </summary>
        public static string HelpWelcomeStep5 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Und wenn du bereit bist, klicke hier, um zur Anmeldung zu gelangen..
        /// </summary>
        public static string HelpWelcomeStep6 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT-Lizenz
        ///Copyright (c) 2022 Maximilian Hammerl
        ///
        ///Jedem, der eine Kopie dieser Software und der zugehörigen Dokumentationsdateien (die „Software“) erhält, wird hiermit kostenlos die Erlaubnis erteilt, ohne Einschränkung mit der Software zu handeln, einschließlich und ohne Einschränkung der Rechte zur Nutzung, zum Kopieren, Ändern, Zusammenführen, Veröffentlichen, Verteilen, Unterlizenzieren und/oder Verkaufen von Kopien der Software, und Personen, denen die Software zur Verfügung gestellt wird, dies unte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geltende Hinweise und Lizenzbedingungen.
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habe die geltenden Hinweise und Lizenzbedingungen gelesen und akzeptiere sie.
        /// </summary>
        public static string LoginAcceptLicense {
            get {
                return ResourceManager.GetString("LoginAcceptLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich erlaube, dass anonyme Daten zum Monitoring und Fehlerverfolgung mittels Sentry gesammelt werden..
        /// </summary>
        public static string LoginAcceptSentry {
            get {
                return ResourceManager.GetString("LoginAcceptSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melde dich mit deinem Rollenspielhimmel Benutzernamen und Passwort an um loszulegen!.
        /// </summary>
        public static string LoginExplanation {
            get {
                return ResourceManager.GetString("LoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit ♡ von.
        /// </summary>
        public static string LoginLove {
            get {
                return ResourceManager.GetString("LoginLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevor du dich einloggen kannst, musst du die geltenden Hinweise und Lizenzbedingungen akzeptieren.
        /// </summary>
        public static string LoginMissingLicense {
            get {
                return ResourceManager.GetString("LoginMissingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib zuerst dein Passwort ein!.
        /// </summary>
        public static string LoginMissingPassword {
            get {
                return ResourceManager.GetString("LoginMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib zuerst deinen Benutzernamen ein!.
        /// </summary>
        public static string LoginMissingUsername {
            get {
                return ResourceManager.GetString("LoginMissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten keine Gruppen geladen werden! Entweder hast du keine Gruppen oder es ist etwas schief gelaufen..
        /// </summary>
        public static string LoginNoGroups {
            get {
                return ResourceManager.GetString("LoginNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Klicke hier, um die geltenden Hinweise und Lizenzbedingungen zu öffnen).
        /// </summary>
        public static string LoginOpenLicense {
            get {
                return ResourceManager.GetString("LoginOpenLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke hier, um mehr über Sentry zu erfahren.
        /// </summary>
        public static string LoginOpenSentry {
            get {
                return ResourceManager.GetString("LoginOpenSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort:.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportiere und sichere deine Rollenspielhimmel Gruppen, Beiträge und Antworten schnell und einfach!.
        /// </summary>
        public static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollenspielhimmel Exporter.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Benutzername:.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du konntest nicht eingeloggt werden! Bitte überprüfe deinen Benutzernamen und dein Passwort..
        /// </summary>
        public static string LoginWrongUsernamePassword {
            get {
                return ResourceManager.GetString("LoginWrongUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bilder der Antworten herunterladen?.
        /// </summary>
        public static string OptionDownloadImages {
            get {
                return ResourceManager.GetString("OptionDownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für jede Antwort die Bilder in einen eigenen Ordner herunterladen?.
        /// </summary>
        public static string OptionDownloadImagesToOwnFolder {
            get {
                return ResourceManager.GetString("OptionDownloadImagesToOwnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für jede Gruppe die Beiträge in ein eigenen Ordner herunterladen?.
        /// </summary>
        public static string OptionDownloadToOwnFolder {
            get {
                return ResourceManager.GetString("OptionDownloadToOwnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Namen der Gruppe am Anfang angeben?.
        /// </summary>
        public static string OptionIncludeGroup {
            get {
                return ResourceManager.GetString("OptionIncludeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch den Eigentümer der Gruppe angeben?.
        /// </summary>
        public static string OptionIncludeGroupAuthor {
            get {
                return ResourceManager.GetString("OptionIncludeGroupAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch angeben, wann die Gruppe erstellt wurde?.
        /// </summary>
        public static string OptionIncludeGroupPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludeGroupPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch die URL der Gruppe angeben?.
        /// </summary>
        public static string OptionIncludeGroupUrl {
            get {
                return ResourceManager.GetString("OptionIncludeGroupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Antworten mit ihren Bildern exportieren?.
        /// </summary>
        public static string OptionIncludeImages {
            get {
                return ResourceManager.GetString("OptionIncludeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Seitenzahl angeben?.
        /// </summary>
        public static string OptionIncludePageNumber {
            get {
                return ResourceManager.GetString("OptionIncludePageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Autor der Antworten angeben?.
        /// </summary>
        public static string OptionIncludePostAuthor {
            get {
                return ResourceManager.GetString("OptionIncludePostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nummer der Antwort angeben?.
        /// </summary>
        public static string OptionIncludePostNumber {
            get {
                return ResourceManager.GetString("OptionIncludePostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angeben, wann die Antwort gepostet wurde?.
        /// </summary>
        public static string OptionIncludePostPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludePostPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Namen des Beitrags am Anfang angeben?.
        /// </summary>
        public static string OptionIncludeThread {
            get {
                return ResourceManager.GetString("OptionIncludeThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch den Autor des Beitrags angeben?.
        /// </summary>
        public static string OptionIncludeThreadAuthor {
            get {
                return ResourceManager.GetString("OptionIncludeThreadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch angeben, wann der Beitrag erstellt wurde?.
        /// </summary>
        public static string OptionIncludeThreadPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludeThreadPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch die URL des Beitrags angeben?.
        /// </summary>
        public static string OptionIncludeThreadUrl {
            get {
                return ResourceManager.GetString("OptionIncludeThreadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Reihenfolge der Beiträge umkehren (von der neuesten zur ältesten statt von der ältesten zur neuesten)?.
        /// </summary>
        public static string OptionReserveOrder {
            get {
                return ResourceManager.GetString("OptionReserveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle zuerst eine Gruppe aus..
        /// </summary>
        public static string SelectGroupFirst {
            get {
                return ResourceManager.GetString("SelectGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Deine Gruppen:.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du musst mindestens eine Gruppe und einen Beitrag auswählen!.
        /// </summary>
        public static string SelectNothingSelected {
            get {
                return ResourceManager.GetString("SelectNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten keine Beiträge für Gruppe {0} geladen werden!.
        /// </summary>
        public static string SelectNoThreadsFor {
            get {
                return ResourceManager.GetString("SelectNoThreadsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gruppen auswählen.
        /// </summary>
        public static string SelectSelectGroups {
            get {
                return ResourceManager.GetString("SelectSelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beiträge auswählen.
        /// </summary>
        public static string SelectSelectThreads {
            get {
                return ResourceManager.GetString("SelectSelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Deine Beiträge:.
        /// </summary>
        public static string SelectThreads {
            get {
                return ResourceManager.GetString("SelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Deine Beiträge von {0}:.
        /// </summary>
        public static string SelectThreadsOf {
            get {
                return ResourceManager.GetString("SelectThreadsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gruppen abwählen.
        /// </summary>
        public static string SelectUnselectGroups {
            get {
                return ResourceManager.GetString("SelectUnselectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beiträge abwählen.
        /// </summary>
        public static string SelectUnselectThreads {
            get {
                return ResourceManager.GetString("SelectUnselectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export starten.
        /// </summary>
        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Export.
        /// </summary>
        public static string ToExport {
            get {
                return ResourceManager.GetString("ToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur eine kleine Vorwarnung, bevor du loslegst: Das Programm befindet sich noch in einer frühen Entwicklungsphase. Es kann sein, dass du auf einige Fehler stößt und einige Funktionen sind noch in der Entwicklung. Vergewissere dich, dass du die aktuellste Version verwendest!
        ///
        ///Wenn du Hilfe benötigst, findest du auf den meisten Seiten oben einen &quot;Hilfe&quot;-Button, der die aktuelle Seite im Detail erklärt. Es gibt auch einen &quot;Feedback&quot;-Button für deine Ideen, Vorschläge und allgemeines Feedback, über das ich mic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke, dass du den RSH Exporter benutzt.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
