//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSHExporter.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSHExporter.Resources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Export Folder:.
        /// </summary>
        public static string ExportChosenFolder {
            get {
                return ResourceManager.GetString("ExportChosenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Export:.
        /// </summary>
        public static string ExportExport {
            get {
                return ResourceManager.GetString("ExportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were successfully exported!.
        /// </summary>
        public static string ExportFilesExported {
            get {
                return ResourceManager.GetString("ExportFilesExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Folder.
        /// </summary>
        public static string ExportFolder {
            get {
                return ResourceManager.GetString("ExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already contains files. Files will be overwritten, if they have the same name. Are you sure that you want to use this folder?.
        /// </summary>
        public static string ExportFolderContainsFiles {
            get {
                return ResourceManager.GetString("ExportFolderContainsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File Format:.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an export folder first!.
        /// </summary>
        public static string ExportMissingFolder {
            get {
                return ResourceManager.GetString("ExportMissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options:.
        /// </summary>
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Selected Groups and Threads:.
        /// </summary>
        public static string ExportSelected {
            get {
                return ResourceManager.GetString("ExportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback will be sent to Maxi! You can also, e.g., include links to images..
        /// </summary>
        public static string FeedbackDetailsDefault {
            get {
                return ResourceManager.GetString("FeedbackDetailsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong unexpectedly! The error has been reported with the ID {0}..
        /// </summary>
        public static string FeedbackDetailsError {
            get {
                return ResourceManager.GetString("FeedbackDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to possibly be contacted, enter your email address here:.
        /// </summary>
        public static string FeedbackEmailDefault {
            get {
                return ResourceManager.GetString("FeedbackEmailDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to be notified by email when the error is fixed, enter your email address here:.
        /// </summary>
        public static string FeedbackEmailError {
            get {
                return ResourceManager.GetString("FeedbackEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your feedback here:.
        /// </summary>
        public static string FeedbackResponseDefault {
            get {
                return ResourceManager.GetString("FeedbackResponseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If possible, please enter more details what you did before the error occured here:.
        /// </summary>
        public static string FeedbackResponseError {
            get {
                return ResourceManager.GetString("FeedbackResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback!.
        /// </summary>
        public static string FeedbackTitleDefault {
            get {
                return ResourceManager.GetString("FeedbackTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        public static string FeedbackTitleError {
            get {
                return ResourceManager.GetString("FeedbackTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Rollenspielhimmel username and password to get started!.
        /// </summary>
        public static string LoginExplanation {
            get {
                return ResourceManager.GetString("LoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With ♡ by.
        /// </summary>
        public static string LoginLove {
            get {
                return ResourceManager.GetString("LoginLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password first!.
        /// </summary>
        public static string LoginMissingPassword {
            get {
                return ResourceManager.GetString("LoginMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username first!.
        /// </summary>
        public static string LoginMissingUsername {
            get {
                return ResourceManager.GetString("LoginMissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups could be loaded! Either you have no groups or something went wrong..
        /// </summary>
        public static string LoginNoGroups {
            get {
                return ResourceManager.GetString("LoginNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password:.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username:.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could not be logged in! Please check your username and password..
        /// </summary>
        public static string LoginWrongUsernamePassword {
            get {
                return ResourceManager.GetString("LoginWrongUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a group first..
        /// </summary>
        public static string SelectGroupFirst {
            get {
                return ResourceManager.GetString("SelectGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Your Groups:.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select at least one group and one thread!.
        /// </summary>
        public static string SelectNothingSelected {
            get {
                return ResourceManager.GetString("SelectNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No threads could be loaded for group {0}!.
        /// </summary>
        public static string SelectNoThreadsFor {
            get {
                return ResourceManager.GetString("SelectNoThreadsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Groups.
        /// </summary>
        public static string SelectSelectGroups {
            get {
                return ResourceManager.GetString("SelectSelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Threads.
        /// </summary>
        public static string SelectSelectThreads {
            get {
                return ResourceManager.GetString("SelectSelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Your Threads:.
        /// </summary>
        public static string SelectThreads {
            get {
                return ResourceManager.GetString("SelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Your Threads of {0}:.
        /// </summary>
        public static string SelectThreadsOf {
            get {
                return ResourceManager.GetString("SelectThreadsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All Groups.
        /// </summary>
        public static string SelectUnselectGroups {
            get {
                return ResourceManager.GetString("SelectUnselectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All Threads.
        /// </summary>
        public static string SelectUnselectThreads {
            get {
                return ResourceManager.GetString("SelectUnselectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Export.
        /// </summary>
        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Export.
        /// </summary>
        public static string ToExport {
            get {
                return ResourceManager.GetString("ToExport", resourceCulture);
            }
        }
    }
}
