//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSHExporter.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSHExporter.Resources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cancel export.
        /// </summary>
        public static string CancelExport {
            get {
                return ResourceManager.GetString("CancelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while exporting! The thread(s) {0} could not be successfully exported!.
        /// </summary>
        public static string ErrorExportFailed {
            get {
                return ResourceManager.GetString("ErrorExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred! Unfortunately, because you have not agreed to the use of Sentry, the error cannot be collected..
        /// </summary>
        public static string ErrorGenericNoSentry {
            get {
                return ResourceManager.GetString("ErrorGenericNoSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the placeholder {0} is missing.
        /// </summary>
        public static string ErrorMissingPlaceholder {
            get {
                return ResourceManager.GetString("ErrorMissingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the placeholders {0} are missing.
        /// </summary>
        public static string ErrorMissingPlaceholders {
            get {
                return ResourceManager.GetString("ErrorMissingPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentry is used to send your feedback. Unfortunately, because you have not agreed to the use of Sentry, your feedback cannot be collected..
        /// </summary>
        public static string ErrorNoSentry {
            get {
                return ResourceManager.GetString("ErrorNoSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with your {0} templates!.
        /// </summary>
        public static string ErrorTemplates {
            get {
                return ResourceManager.GetString("ErrorTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the placeholder {0} is unused.
        /// </summary>
        public static string ErrorUnusedPlaceholder {
            get {
                return ResourceManager.GetString("ErrorUnusedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the placeholders {0} are unused.
        /// </summary>
        public static string ErrorUnusedPlaceholders {
            get {
                return ResourceManager.GetString("ErrorUnusedPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options for Advanced Users:.
        /// </summary>
        public static string ExportAdvancedOptions {
            get {
                return ResourceManager.GetString("ExportAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the export?.
        /// </summary>
        public static string ExportCancelExportQuestion {
            get {
                return ResourceManager.GetString("ExportCancelExportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Folder:.
        /// </summary>
        public static string ExportChosenFolder {
            get {
                return ResourceManager.GetString("ExportChosenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Export:.
        /// </summary>
        public static string ExportExport {
            get {
                return ResourceManager.GetString("ExportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One file was successfully exported!.
        /// </summary>
        public static string ExportFileExported {
            get {
                return ResourceManager.GetString("ExportFileExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were successfully exported!.
        /// </summary>
        public static string ExportFilesExported {
            get {
                return ResourceManager.GetString("ExportFilesExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Folder.
        /// </summary>
        public static string ExportFolder {
            get {
                return ResourceManager.GetString("ExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already contains files. Files will be overwritten, if they have the same name. Are you sure that you want to use this folder?.
        /// </summary>
        public static string ExportFolderContainsFilesQuestion {
            get {
                return ResourceManager.GetString("ExportFolderContainsFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File Format:.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one export file format!.
        /// </summary>
        public static string ExportMissingFileFormat {
            get {
                return ResourceManager.GetString("ExportMissingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an export folder first!.
        /// </summary>
        public static string ExportMissingFolder {
            get {
                return ResourceManager.GetString("ExportMissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Export Options:.
        /// </summary>
        public static string ExportOtherOptions {
            get {
                return ResourceManager.GetString("ExportOtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Selected Groups and Threads:.
        /// </summary>
        public static string ExportSelected {
            get {
                return ResourceManager.GetString("ExportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Text Options:.
        /// </summary>
        public static string ExportTextOptions {
            get {
                return ResourceManager.GetString("ExportTextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback will be sent to Maxi! You can also, e.g., include links to images..
        /// </summary>
        public static string FeedbackDetailsDefault {
            get {
                return ResourceManager.GetString("FeedbackDetailsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong unexpectedly! The error has been reported with the ID {0}..
        /// </summary>
        public static string FeedbackDetailsError {
            get {
                return ResourceManager.GetString("FeedbackDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to possibly be contacted, enter your email address here:.
        /// </summary>
        public static string FeedbackEmailDefault {
            get {
                return ResourceManager.GetString("FeedbackEmailDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to be notified by email when the error is fixed, enter your email address here:.
        /// </summary>
        public static string FeedbackEmailError {
            get {
                return ResourceManager.GetString("FeedbackEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your feedback here:.
        /// </summary>
        public static string FeedbackResponseDefault {
            get {
                return ResourceManager.GetString("FeedbackResponseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If possible, please enter more details what you did before the error occured here:.
        /// </summary>
        public static string FeedbackResponseError {
            get {
                return ResourceManager.GetString("FeedbackResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback!.
        /// </summary>
        public static string FeedbackTitleDefault {
            get {
                return ResourceManager.GetString("FeedbackTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        public static string FeedbackTitleError {
            get {
                return ResourceManager.GetString("FeedbackTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word File (.docx) - Contains text and (if selected) images.
        /// </summary>
        public static string FileFormatDocx {
            get {
                return ResourceManager.GetString("FileFormatDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File (.html) - Contains formatted text and (if selected) images.
        /// </summary>
        public static string FileFormatHtml {
            get {
                return ResourceManager.GetString("FileFormatHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (.txt) - Contains text only, no images and no formatting.
        /// </summary>
        public static string FileFormatTxt {
            get {
                return ResourceManager.GetString("FileFormatTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First check whether you have selected all groups and threads you want to export..
        /// </summary>
        public static string HelpExportStep1 {
            get {
                return ResourceManager.GetString("HelpExportStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always go back to selecting groups and threads. All of your changes are automatically saved..
        /// </summary>
        public static string HelpExportStep2 {
            get {
                return ResourceManager.GetString("HelpExportStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the export process by choosing the folder the files should be saved in. Files will be overwritten, if they already exist..
        /// </summary>
        public static string HelpExportStep3 {
            get {
                return ResourceManager.GetString("HelpExportStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then choose the format (or multiple formats) of the exported files..
        /// </summary>
        public static string HelpExportStep4 {
            get {
                return ResourceManager.GetString("HelpExportStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure how you want the groups and threads to be exported..
        /// </summary>
        public static string HelpExportStep5 {
            get {
                return ResourceManager.GetString("HelpExportStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of using the checkboxes of the previous step, advanced users can also edit the export templates directly. This required basic knowledge of HTML..
        /// </summary>
        public static string HelpExportStep6 {
            get {
                return ResourceManager.GetString("HelpExportStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also configure where the files will be saved, whether all files should be in one folder or whether every group and/or all images of a thread should have their separate folder..
        /// </summary>
        public static string HelpExportStep7 {
            get {
                return ResourceManager.GetString("HelpExportStep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, you can start the export here. (Exporting can take a while, especially with a slow internet connection.) You can also cancel the export at any time..
        /// </summary>
        public static string HelpExportStep8 {
            get {
                return ResourceManager.GetString("HelpExportStep8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First enter the username and password you use on Rollenspielhimmel to log in..
        /// </summary>
        public static string HelpLoginStep1 {
            get {
                return ResourceManager.GetString("HelpLoginStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then click here to log in and continue with selecting your groups and threads..
        /// </summary>
        public static string HelpLoginStep2 {
            get {
                return ResourceManager.GetString("HelpLoginStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by selecting the groups. Clicking on a group will load all threads of it..
        /// </summary>
        public static string HelpSelectStep1 {
            get {
                return ResourceManager.GetString("HelpSelectStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, for each group, select the posts you want to export..
        /// </summary>
        public static string HelpSelectStep2 {
            get {
                return ResourceManager.GetString("HelpSelectStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select und unselect all groups and/or threads..
        /// </summary>
        public static string HelpSelectStep3 {
            get {
                return ResourceManager.GetString("HelpSelectStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can open a group or thread in the browser by clicking on the small icon to the right of the group or thread name..
        /// </summary>
        public static string HelpSelectStep4 {
            get {
                return ResourceManager.GetString("HelpSelectStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have selected all groups and threads, continue to export by clicking here. (You can also go back again without losing any of your changes.).
        /// </summary>
        public static string HelpSelectStep5 {
            get {
                return ResourceManager.GetString("HelpSelectStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        public static string HelpStep {
            get {
                return ResourceManager.GetString("HelpStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! These help dialogs will hopefully help you with learning how to use this program. Most pages have a help dialog which explains how the current page works..
        /// </summary>
        public static string HelpWelcomeStep1 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowing Sentry to collect anonymous data when an error occurs helps me immensily with fixing these errors..
        /// </summary>
        public static string HelpWelcomeStep2 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can click here to go to the repository of the program..
        /// </summary>
        public static string HelpWelcomeStep3 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see the current version number of the program..
        /// </summary>
        public static string HelpWelcomeStep4 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And here the team which helps me with designing and programming..
        /// </summary>
        public static string HelpWelcomeStep5 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And if you are ready, click here to continue to the login..
        /// </summary>
        public static string HelpWelcomeStep6 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///Copyright (c) 2022 Maximilian Hammerl
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright noti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable Notes and License Terms.
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the applicable notices and license terms.
        /// </summary>
        public static string LoginAcceptLicense {
            get {
                return ResourceManager.GetString("LoginAcceptLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I allow anonymous data to be collected for application monitoring and error tracking using Sentry..
        /// </summary>
        public static string LoginAcceptSentry {
            get {
                return ResourceManager.GetString("LoginAcceptSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Rollenspielhimmel username and password to get started!.
        /// </summary>
        public static string LoginExplanation {
            get {
                return ResourceManager.GetString("LoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With ♡ by.
        /// </summary>
        public static string LoginLove {
            get {
                return ResourceManager.GetString("LoginLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to accept the applicable notices and license terms before you can login.
        /// </summary>
        public static string LoginMissingLicense {
            get {
                return ResourceManager.GetString("LoginMissingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password first!.
        /// </summary>
        public static string LoginMissingPassword {
            get {
                return ResourceManager.GetString("LoginMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username first!.
        /// </summary>
        public static string LoginMissingUsername {
            get {
                return ResourceManager.GetString("LoginMissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups could be loaded! Either you have no groups or something went wrong..
        /// </summary>
        public static string LoginNoGroups {
            get {
                return ResourceManager.GetString("LoginNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click here to open the applicable notices and license terms).
        /// </summary>
        public static string LoginOpenLicense {
            get {
                return ResourceManager.GetString("LoginOpenLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to learn more out Sentry.
        /// </summary>
        public static string LoginOpenSentry {
            get {
                return ResourceManager.GetString("LoginOpenSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password:.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly and easily export and backup your Rollenspielhimmel groups, threads and posts!.
        /// </summary>
        public static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollenspielhimmel Exporter.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username:.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could not be logged in! Please check your username and password..
        /// </summary>
        public static string LoginWrongUsernamePassword {
            get {
                return ResourceManager.GetString("LoginWrongUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the images of the posts?.
        /// </summary>
        public static string OptionDownloadImages {
            get {
                return ResourceManager.GetString("OptionDownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the images for each post into a separate folder?.
        /// </summary>
        public static string OptionDownloadImagesToOwnFolder {
            get {
                return ResourceManager.GetString("OptionDownloadImagesToOwnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the threads for each group into a separate folder?.
        /// </summary>
        public static string OptionDownloadToOwnFolder {
            get {
                return ResourceManager.GetString("OptionDownloadToOwnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the group at the top?.
        /// </summary>
        public static string OptionIncludeGroup {
            get {
                return ResourceManager.GetString("OptionIncludeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also include the owner of the group?.
        /// </summary>
        public static string OptionIncludeGroupAuthor {
            get {
                return ResourceManager.GetString("OptionIncludeGroupAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also include when the group was created?.
        /// </summary>
        public static string OptionIncludeGroupPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludeGroupPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also include the URL to the group?.
        /// </summary>
        public static string OptionIncludeGroupUrl {
            get {
                return ResourceManager.GetString("OptionIncludeGroupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the posts with its images?.
        /// </summary>
        public static string OptionIncludeImages {
            get {
                return ResourceManager.GetString("OptionIncludeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the page number?.
        /// </summary>
        public static string OptionIncludePageNumber {
            get {
                return ResourceManager.GetString("OptionIncludePageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the author of the posts?.
        /// </summary>
        public static string OptionIncludePostAuthor {
            get {
                return ResourceManager.GetString("OptionIncludePostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the post number?.
        /// </summary>
        public static string OptionIncludePostNumber {
            get {
                return ResourceManager.GetString("OptionIncludePostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include when the post was posted?.
        /// </summary>
        public static string OptionIncludePostPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludePostPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the thread at the top?.
        /// </summary>
        public static string OptionIncludeThread {
            get {
                return ResourceManager.GetString("OptionIncludeThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also include the author of the thread?.
        /// </summary>
        public static string OptionIncludeThreadAuthor {
            get {
                return ResourceManager.GetString("OptionIncludeThreadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also include when the thread was created?.
        /// </summary>
        public static string OptionIncludeThreadPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludeThreadPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also include the URL to the thread?.
        /// </summary>
        public static string OptionIncludeThreadUrl {
            get {
                return ResourceManager.GetString("OptionIncludeThreadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse the order of the posts (newest to oldest instead of oldest to newest)?.
        /// </summary>
        public static string OptionReserveOrder {
            get {
                return ResourceManager.GetString("OptionReserveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Templates.
        /// </summary>
        public static string OptionUseCustomTemplates {
            get {
                return ResourceManager.GetString("OptionUseCustomTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CurrentPostNumber].
        /// </summary>
        public static string PlaceholderCurrentPostNumber {
            get {
                return ResourceManager.GetString("PlaceholderCurrentPostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GroupOwner].
        /// </summary>
        public static string PlaceholderGroupAuthor {
            get {
                return ResourceManager.GetString("PlaceholderGroupAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GroupCreatedAt].
        /// </summary>
        public static string PlaceholderGroupPostedAt {
            get {
                return ResourceManager.GetString("PlaceholderGroupPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GroupName].
        /// </summary>
        public static string PlaceholderGroupTitle {
            get {
                return ResourceManager.GetString("PlaceholderGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GroupUrl].
        /// </summary>
        public static string PlaceholderGroupUrl {
            get {
                return ResourceManager.GetString("PlaceholderGroupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PostAuthor].
        /// </summary>
        public static string PlaceholderPostAuthor {
            get {
                return ResourceManager.GetString("PlaceholderPostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PostPostedAt].
        /// </summary>
        public static string PlaceholderPostPostedAt {
            get {
                return ResourceManager.GetString("PlaceholderPostPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Posts].
        /// </summary>
        public static string PlaceholderPosts {
            get {
                return ResourceManager.GetString("PlaceholderPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PostText].
        /// </summary>
        public static string PlaceholderPostText {
            get {
                return ResourceManager.GetString("PlaceholderPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ThreadAuthor].
        /// </summary>
        public static string PlaceholderThreadAuthor {
            get {
                return ResourceManager.GetString("PlaceholderThreadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ThreadCreatedAt].
        /// </summary>
        public static string PlaceholderThreadPostedAt {
            get {
                return ResourceManager.GetString("PlaceholderThreadPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ThreadName].
        /// </summary>
        public static string PlaceholderThreadTitle {
            get {
                return ResourceManager.GetString("PlaceholderThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ThreadUrl].
        /// </summary>
        public static string PlaceholderThreadUrl {
            get {
                return ResourceManager.GetString("PlaceholderThreadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TotalPostNumber].
        /// </summary>
        public static string PlaceholderTotalPostNumber {
            get {
                return ResourceManager.GetString("PlaceholderTotalPostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset:.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With All Placeholders.
        /// </summary>
        public static string ResetAllPlaceholders {
            get {
                return ResourceManager.GetString("ResetAllPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Current Placeholders.
        /// </summary>
        public static string ResetCurrentPlaceholders {
            get {
                return ResourceManager.GetString("ResetCurrentPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a group first..
        /// </summary>
        public static string SelectGroupFirst {
            get {
                return ResourceManager.GetString("SelectGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Your Groups:.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select at least one group and one thread!.
        /// </summary>
        public static string SelectNothingSelected {
            get {
                return ResourceManager.GetString("SelectNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No threads could be loaded for group {0}!.
        /// </summary>
        public static string SelectNoThreadsFor {
            get {
                return ResourceManager.GetString("SelectNoThreadsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Groups.
        /// </summary>
        public static string SelectSelectGroups {
            get {
                return ResourceManager.GetString("SelectSelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Groups and Threads.
        /// </summary>
        public static string SelectSelectGroupsThreads {
            get {
                return ResourceManager.GetString("SelectSelectGroupsThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Threads.
        /// </summary>
        public static string SelectSelectThreads {
            get {
                return ResourceManager.GetString("SelectSelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Your Threads:.
        /// </summary>
        public static string SelectThreads {
            get {
                return ResourceManager.GetString("SelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Your Threads of {0}:.
        /// </summary>
        public static string SelectThreadsOf {
            get {
                return ResourceManager.GetString("SelectThreadsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All Groups.
        /// </summary>
        public static string SelectUnselectGroups {
            get {
                return ResourceManager.GetString("SelectUnselectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All Groups and Threads.
        /// </summary>
        public static string SelectUnselectGroupsThreads {
            get {
                return ResourceManager.GetString("SelectUnselectGroupsThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All Threads.
        /// </summary>
        public static string SelectUnselectThreads {
            get {
                return ResourceManager.GetString("SelectUnselectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Export.
        /// </summary>
        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string TemplateAt {
            get {
                return ResourceManager.GetString("TemplateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string TemplateFrom {
            get {
                return ResourceManager.GetString("TemplateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image at.
        /// </summary>
        public static string TemplateImageAt {
            get {
                return ResourceManager.GetString("TemplateImageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string TemplateOn {
            get {
                return ResourceManager.GetString("TemplateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string TemplatePage {
            get {
                return ResourceManager.GetString("TemplatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text file export uses the text templates. The HTML file and Word file export use the HTML templates. The head templates stand for the header of the export of a thread and the body templates for the answers of the thread. At the placeholder.
        /// </summary>
        public static string TemplatesDetails1 {
            get {
                return ResourceManager.GetString("TemplatesDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the head templates the body templates for the answers are inserted when exporting.
        ///
        ///The default templates are based on the current export text options. Only if a text option is selected, the placeholder is also displayed in the default template..
        /// </summary>
        public static string TemplatesDetails2 {
            get {
                return ResourceManager.GetString("TemplatesDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body-Template for Html.
        /// </summary>
        public static string TemplatesHtmlBody {
            get {
                return ResourceManager.GetString("TemplatesHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head-Template for Html.
        /// </summary>
        public static string TemplatesHtmlHead {
            get {
                return ResourceManager.GetString("TemplatesHtmlHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional:.
        /// </summary>
        public static string TemplatesOptionalPlaceholders {
            get {
                return ResourceManager.GetString("TemplatesOptionalPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Placeholders.
        /// </summary>
        public static string TemplatesPlaceholders {
            get {
                return ResourceManager.GetString("TemplatesPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required:.
        /// </summary>
        public static string TemplatesRequiredPlaceholders {
            get {
                return ResourceManager.GetString("TemplatesRequiredPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body-Template for Text.
        /// </summary>
        public static string TemplatesTextBody {
            get {
                return ResourceManager.GetString("TemplatesTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head-Template for Text.
        /// </summary>
        public static string TemplatesTextHead {
            get {
                return ResourceManager.GetString("TemplatesTextHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Templates.
        /// </summary>
        public static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Export.
        /// </summary>
        public static string ToExport {
            get {
                return ResourceManager.GetString("ToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Templates.
        /// </summary>
        public static string UpdateTemplates {
            get {
                return ResourceManager.GetString("UpdateTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export was cancelled. Some files may have already been exported..
        /// </summary>
        public static string WarningExportCancelled {
            get {
                return ResourceManager.GetString("WarningExportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wäre super, falls du Sentry erlauben könntest, Fehler zu verfolgen! Darf Sentry anonyme Daten sammeln, wenn ein Fehler auftritt?.
        /// </summary>
        public static string WelcomeAllowSentryQuestion {
            get {
                return ResourceManager.GetString("WelcomeAllowSentryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a heads-up before you jump in: The program is still in early development. You might experience some bugs and some features are still being developed. Make sure that you are using the most recent version!
        ///
        ///If you need help, most pages have a &quot;Help&quot; button at the top which explains the current page in detail. There is also a &quot;Feedback&quot; button for your ideas, suggestions and general feedback which I am always happy to receive.
        ///
        ///To simplify finding and fixing possible bugs, this program uses Sentry, a  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using the RSH Exporter.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
