version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/PostExporter"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
