//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostExporter.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostExporter.Resources.Localization.Resources.de", typeof(Resources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptieren.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zum Export.
        /// </summary>
        public static string BackToExport {
            get {
                return ResourceManager.GetString("BackToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken, um den Export abzubrechen.
        /// </summary>
        public static string CancelExport {
            get {
                return ResourceManager.GetString("CancelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter schließen.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablehnen.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Beiträge konnten nicht exportiert werden, weil dem Exporter der Zugriff auf den Export-Ordner verweigert wurde, möglicherweise durch ein Antivirensystem oder Windows:.
        /// </summary>
        public static string ErrorExportFailedDirectoryAccess {
            get {
                return ResourceManager.GetString("ErrorExportFailedDirectoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Beiträge konnten nicht exportiert werden, weil der Download eines Bildes fehlgeschlagen ist, weil du entweder von dem Server, der das Bild hostet, blockiert wurdest, weil deine Internetverbindung nicht stabil ist oder weil das Bild nicht mehr verfügbar ist:.
        /// </summary>
        public static string ErrorExportFailedImageDownload {
            get {
                return ResourceManager.GetString("ErrorExportFailedImageDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Beiträge konnten nicht exportiert werden, weil keine Beiträge geladen werden konnten (wenn das ein Fehler ist, kontaktiere mich bitte über den Feedback-Dialog):.
        /// </summary>
        public static string ErrorExportFailedNoPosts {
            get {
                return ResourceManager.GetString("ErrorExportFailedNoPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Beiträge konnten nicht exportiert werden, weil ein nicht erkannter Fehler aufgetreten ist:.
        /// </summary>
        public static string ErrorExportFailedUnrecognized {
            get {
                return ResourceManager.GetString("ErrorExportFailedUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Beiträge konnten nicht exportiert werden, weil der Export eines Bildes fehlgeschlagen ist (höchstwahrscheinlich für den Word-Export), weil du entweder von dem Server, der das Bild hostet, blockiert wurdest, weil deine Internetverbindung nicht stabil ist oder weil das Bild nicht mehr verfügbar ist:.
        /// </summary>
        public static string ErrorExportFailedWordImageExport {
            get {
                return ResourceManager.GetString("ErrorExportFailedWordImageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten!.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to der Platzhalter {0} fehlt.
        /// </summary>
        public static string ErrorMissingPlaceholder {
            get {
                return ResourceManager.GetString("ErrorMissingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to die Platzhalter {0} fehlen.
        /// </summary>
        public static string ErrorMissingPlaceholders {
            get {
                return ResourceManager.GetString("ErrorMissingPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten keine Gruppen geladen werden! Entweder hast du keine Gruppen oder es ist etwas schief gelaufen..
        /// </summary>
        public static string ErrorNoGroups {
            get {
                return ResourceManager.GetString("ErrorNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentry wird verwendet, um dein Feedback zu senden. Da du der Verwendung von Sentry nicht zugestimmt hast, kann dein Feedback leider nicht erfasst werden..
        /// </summary>
        public static string ErrorNoSentry {
            get {
                return ResourceManager.GetString("ErrorNoSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Fehler konnte nicht gemeldet werden, weil Sentry keine Fehler sammeln darf..
        /// </summary>
        public static string ErrorNotReportedToSentry {
            get {
                return ResourceManager.GetString("ErrorNotReportedToSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Fehler wurde mit Sentry gemeldet und wird hoffentlich bald behoben!.
        /// </summary>
        public static string ErrorReportedToSentry {
            get {
                return ResourceManager.GetString("ErrorReportedToSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Forum-Server ist im Moment nicht erreichbar. Versuche es in ein paar Minuten noch einmal!.
        /// </summary>
        public static string ErrorServerUnavailable {
            get {
                return ResourceManager.GetString("ErrorServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manche Gruppen konnten nicht geladen werden!.
        /// </summary>
        public static string ErrorSomeGroupsFailedToLoad {
            get {
                return ResourceManager.GetString("ErrorSomeGroupsFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manche Beiträge von Gruppe {0} konnten nicht geladen werden.
        /// </summary>
        public static string ErrorSomeThreadsFailedToLoad {
            get {
                return ResourceManager.GetString("ErrorSomeThreadsFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt ein Problem mit deinen {0} Templates!.
        /// </summary>
        public static string ErrorTemplates {
            get {
                return ResourceManager.GetString("ErrorTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem Exporter wurde der Zugriff auf den von dir ausgewählten Ordner verweigert. Möglicherweise sperrt ein Antivirensystem oder Windows das Programm..
        /// </summary>
        public static string ErrorUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to der Platzhalter {0} ist unbenutzt.
        /// </summary>
        public static string ErrorUnusedPlaceholder {
            get {
                return ResourceManager.GetString("ErrorUnusedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to die Platzhalter {0} sind unbenutzt.
        /// </summary>
        public static string ErrorUnusedPlaceholders {
            get {
                return ResourceManager.GetString("ErrorUnusedPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Optionen für fortgeschrittene Benutzer:.
        /// </summary>
        public static string ExportAdvancedOptions {
            get {
                return ResourceManager.GetString("ExportAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du den Export abbrechen?.
        /// </summary>
        public static string ExportCancelExportQuestion {
            get {
                return ResourceManager.GetString("ExportCancelExportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Ordner:.
        /// </summary>
        public static string ExportChosenFolder {
            get {
                return ResourceManager.GetString("ExportChosenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Export:.
        /// </summary>
        public static string ExportExport {
            get {
                return ResourceManager.GetString("ExportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Ordner.
        /// </summary>
        public static string ExportFolder {
            get {
                return ResourceManager.GetString("ExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Ordner enthält bereits Dateien. Dateien werden überschrieben, wenn sie denselben Namen haben. Bist du sicher, dass du diesen Ordner verwenden möchtest?.
        /// </summary>
        public static string ExportFolderContainsFilesQuestion {
            get {
                return ResourceManager.GetString("ExportFolderContainsFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Dateiformat:.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Export-Optionen:.
        /// </summary>
        public static string ExportOtherOptions {
            get {
                return ResourceManager.GetString("ExportOtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Ergebnis.
        /// </summary>
        public static string ExportResultTitle {
            get {
                return ResourceManager.GetString("ExportResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Ausgewählte Gruppen und Beiträge:.
        /// </summary>
        public static string ExportSelected {
            get {
                return ResourceManager.GetString("ExportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Text-Optionen:.
        /// </summary>
        public static string ExportTextOptions {
            get {
                return ResourceManager.GetString("ExportTextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst z.B. auch Links zu Bildern einfügen..
        /// </summary>
        public static string FeedbackDetailsDefault {
            get {
                return ResourceManager.GetString("FeedbackDetailsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etwas ist unerwartet schief gelaufen! Der Fehler wurde mit der ID {0} registriert..
        /// </summary>
        public static string FeedbackDetailsError {
            get {
                return ResourceManager.GetString("FeedbackDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du lieber per E-Mail kontaktiert werden möchtest, kannst du hier deine E-Mail-Adresse eingeben:.
        /// </summary>
        public static string FeedbackEmailDefault {
            get {
                return ResourceManager.GetString("FeedbackEmailDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib dein Feedback hier ein:.
        /// </summary>
        public static string FeedbackResponseDefault {
            get {
                return ResourceManager.GetString("FeedbackResponseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn möglich, gib hier bitte mehr Details darüber an, was du getan hast, bevor der Fehler aufgetreten ist:.
        /// </summary>
        public static string FeedbackResponseError {
            get {
                return ResourceManager.GetString("FeedbackResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke für dein Feedback!.
        /// </summary>
        public static string FeedbackTitleDefault {
            get {
                return ResourceManager.GetString("FeedbackTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten!.
        /// </summary>
        public static string FeedbackTitleError {
            get {
                return ResourceManager.GetString("FeedbackTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn ich (der Entwickler des Exporters) dich für Fragen kontaktieren darf, gib hier deinen Benutzernamen ein:.
        /// </summary>
        public static string FeedbackUsernameDefault {
            get {
                return ResourceManager.GetString("FeedbackUsernameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word-Datei (.docx) - Enthält Text und (wenn ausgewählt) Bilder.
        /// </summary>
        public static string FileFormatDocx {
            get {
                return ResourceManager.GetString("FileFormatDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML-Datei (.html) - Enthält formatierten Text und (wenn ausgewählt) Bilder.
        /// </summary>
        public static string FileFormatHtml {
            get {
                return ResourceManager.GetString("FileFormatHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-Datei (.txt) - Enthält nur Text, keine Formatierung und keine Bilder.
        /// </summary>
        public static string FileFormatTxt {
            get {
                return ResourceManager.GetString("FileFormatTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfe zunächst, ob du alle Gruppen und Beiträge ausgewählt hast, die du exportieren möchtest..
        /// </summary>
        public static string HelpExportStep1 {
            get {
                return ResourceManager.GetString("HelpExportStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst jederzeit zurückgehen, um Gruppen und Themen auszuwählen. Alle deine Änderungen werden automatisch gespeichert..
        /// </summary>
        public static string HelpExportStep2 {
            get {
                return ResourceManager.GetString("HelpExportStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginne den Exportvorgang, indem du den Ordner auswählst, in dem die Dateien gespeichert werden sollen. Dateien werden überschrieben, wenn sie bereits existieren..
        /// </summary>
        public static string HelpExportStep3 {
            get {
                return ResourceManager.GetString("HelpExportStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle dann das Format (oder mehrere Formate) für die exportierten Dateien..
        /// </summary>
        public static string HelpExportStep4 {
            get {
                return ResourceManager.GetString("HelpExportStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lege fest, wie die Gruppen und Beiträge exportiert werden sollen..
        /// </summary>
        public static string HelpExportStep5 {
            get {
                return ResourceManager.GetString("HelpExportStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anstatt die Checkboxes des vorherigen Schritts zu verwenden, können fortgeschrittene Benutzer die Export-Templates auch direkt bearbeiten. Dafür sind Grundkenntnisse in HTML erforderlich..
        /// </summary>
        public static string HelpExportStep6 {
            get {
                return ResourceManager.GetString("HelpExportStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst auch konfigurieren, wo die Dateien gespeichert werden sollen, ob alle Dateien in einem Ordner sein sollen oder ob jede Gruppe und/oder alle Bilder eines Beitrags einen eigenen Ordner haben sollen..
        /// </summary>
        public static string HelpExportStep7 {
            get {
                return ResourceManager.GetString("HelpExportStep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschließend kannst du den Export hier starten. (Der Export kann eine Weile dauern, besonders bei einer langsamen Internetverbindung.) Du kannst den Export auch jederzeit abbrechen..
        /// </summary>
        public static string HelpExportStep8 {
            get {
                return ResourceManager.GetString("HelpExportStep8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib zunächst hier die URL des Forums ein..
        /// </summary>
        public static string HelpLoginStep1 {
            get {
                return ResourceManager.GetString("HelpLoginStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib dann den Benutzernamen und das Passwort ein, mit denen du dich im Forum anmeldest..
        /// </summary>
        public static string HelpLoginStep2 {
            get {
                return ResourceManager.GetString("HelpLoginStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du fertig bist, klicke hier, um dich einzuloggen und mit der Auswahl deiner Gruppen und Themen fortzufahren..
        /// </summary>
        public static string HelpLoginStep3 {
            get {
                return ResourceManager.GetString("HelpLoginStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginne damit, die Gruppen auszuwählen. Wenn du auf eine Gruppe klickst, werden alle Beiträge dieser Gruppe geladen..
        /// </summary>
        public static string HelpSelectStep1 {
            get {
                return ResourceManager.GetString("HelpSelectStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle dann für jede Gruppe die Beiträge aus, die du exportieren möchtest..
        /// </summary>
        public static string HelpSelectStep2 {
            get {
                return ResourceManager.GetString("HelpSelectStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du alle Gruppen und/oder Beiträge an- und abwählen..
        /// </summary>
        public static string HelpSelectStep3 {
            get {
                return ResourceManager.GetString("HelpSelectStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst eine Gruppe oder einen Beitrag im Browser öffnen, indem du auf das kleine Symbol rechts neben dem Namen der Gruppe oder des Beitrags klickst..
        /// </summary>
        public static string HelpSelectStep4 {
            get {
                return ResourceManager.GetString("HelpSelectStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du alle Gruppen und Beiträge ausgewählt hast, fahre mit dem Export fort, indem du hier klickst. (Du kannst auch wieder zurückgehen, ohne dass deine Änderungen verloren gehen.).
        /// </summary>
        public static string HelpSelectStep5 {
            get {
                return ResourceManager.GetString("HelpSelectStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schritt {0} von {1}.
        /// </summary>
        public static string HelpStep {
            get {
                return ResourceManager.GetString("HelpStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo! Diese Hilfedialoge helfen dir hoffentlich dabei, zu lernen, wie du dieses Programm benutzen kannst. Die meisten Seiten haben einen Hilfedialog, der erklärt, wie die aktuelle Seite funktioniert..
        /// </summary>
        public static string HelpWelcomeStep1 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du Sentry erlaubst, Daten zu sammeln, wenn ein Fehler auftritt, hilft mir das ungemein bei der Behebung dieser Fehler..
        /// </summary>
        public static string HelpWelcomeStep2 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst hier klicken, um zum Repository des Programms zu gelangen..
        /// </summary>
        public static string HelpWelcomeStep3 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du die aktuelle Versionsnummer des Programms sehen..
        /// </summary>
        public static string HelpWelcomeStep4 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Und hier das Team, das mir bei der Gestaltung und Programmierung hilft..
        /// </summary>
        public static string HelpWelcomeStep5 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Und wenn du bereit bist, klicke hier, um zur Anmeldung zu gelangen..
        /// </summary>
        public static string HelpWelcomeStep6 {
            get {
                return ResourceManager.GetString("HelpWelcomeStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorieren.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beiträge wurden erfolgreich exportiert:.
        /// </summary>
        public static string InfoAllThreadsSuccessfullyExported {
            get {
                return ResourceManager.GetString("InfoAllThreadsSuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Export wurde abgebrochen. Manche der folgenden Beiträge wurden möglicherweise bereits exportiert:.
        /// </summary>
        public static string InfoCancelledThreadsExported {
            get {
                return ResourceManager.GetString("InfoCancelledThreadsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Beiträge wurden erfolgreich exportiert:.
        /// </summary>
        public static string InfoThreadsSuccessfullyExported {
            get {
                return ResourceManager.GetString("InfoThreadsSuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT-Lizenz
        ///Copyright (c) 2022 Maximilian Hammerl
        ///
        ///Jedem, der eine Kopie dieser Software und der zugehörigen Dokumentationsdateien (die „Software“) erhält, wird hiermit kostenlos die Erlaubnis erteilt, ohne Einschränkung mit der Software zu handeln, einschließlich und ohne Einschränkung der Rechte zur Nutzung, zum Kopieren, Ändern, Zusammenführen, Veröffentlichen, Verteilen, Unterlizenzieren und/oder Verkaufen von Kopien der Software, und Personen, denen die Software zur Verfügung gestellt wird, dies unte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geltende Hinweise und Lizenzbedingungen.
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habe die geltenden Hinweise und Lizenzbedingungen gelesen und akzeptiere sie.
        /// </summary>
        public static string LoginAcceptLicense {
            get {
                return ResourceManager.GetString("LoginAcceptLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich erlaube, dass Daten zum Monitoring und Fehlerverfolgung mittels Sentry gesammelt werden..
        /// </summary>
        public static string LoginAcceptSentry {
            get {
                return ResourceManager.GetString("LoginAcceptSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL des Forums:.
        /// </summary>
        public static string LoginBaseUrl {
            get {
                return ResourceManager.GetString("LoginBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die URL sollte ähnlich aussehen wie &quot;the-forum.de&quot; oder &quot;the-forum.yooco.de&quot;..
        /// </summary>
        public static string LoginBaseUrlHelp {
            get {
                return ResourceManager.GetString("LoginBaseUrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melde dich mit deinem Benutzernamen und Passwort an um loszulegen!.
        /// </summary>
        public static string LoginExplanation {
            get {
                return ResourceManager.GetString("LoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit ♡ von.
        /// </summary>
        public static string LoginLove {
            get {
                return ResourceManager.GetString("LoginLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevor du dich einloggen kannst, musst du die geltenden Hinweise und Lizenzbedingungen akzeptieren.
        /// </summary>
        public static string LoginMissingLicense {
            get {
                return ResourceManager.GetString("LoginMissingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Klicke hier, um die geltenden Hinweise und Lizenzbedingungen zu öffnen).
        /// </summary>
        public static string LoginOpenLicense {
            get {
                return ResourceManager.GetString("LoginOpenLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke hier, um mehr über Sentry zu erfahren.
        /// </summary>
        public static string LoginOpenSentry {
            get {
                return ResourceManager.GetString("LoginOpenSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort:.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort merken?.
        /// </summary>
        public static string LoginRememberPassword {
            get {
                return ResourceManager.GetString("LoginRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinen Benutzername merken?.
        /// </summary>
        public static string LoginRememberUsername {
            get {
                return ResourceManager.GetString("LoginRememberUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportiere und sichere deine Gruppen, Beiträge und Antworten schnell und einfach!.
        /// </summary>
        public static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Exporter.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Benutzername:.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um die neueste Version herunterzuladen, klicke bitte hier:.
        /// </summary>
        public static string NewReleaseClickToDownload {
            get {
                return ResourceManager.GetString("NewReleaseClickToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du verwendest derzeit Version.
        /// </summary>
        public static string NewReleaseDetails1 {
            get {
                return ResourceManager.GetString("NewReleaseDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die aktuellste Version des Post Exporters ist Version.
        /// </summary>
        public static string NewReleaseDetails2 {
            get {
                return ResourceManager.GetString("NewReleaseDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte aktualisiere auf die neueste Version, um die neuesten Funktionen und Fehlerbehebungen zu nutzen..
        /// </summary>
        public static string NewReleaseDetails3 {
            get {
                return ResourceManager.GetString("NewReleaseDetails3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Informationen findest du in den.
        /// </summary>
        public static string NewReleaseMoreInfo1 {
            get {
                return ResourceManager.GetString("NewReleaseMoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionshinweisen auf dem GitHub-Repository.
        /// </summary>
        public static string NewReleaseMoreInfo2 {
            get {
                return ResourceManager.GetString("NewReleaseMoreInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt eine neue Version des Post Exporters!.
        /// </summary>
        public static string NewReleaseTitle {
            get {
                return ResourceManager.GetString("NewReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ kannst du auch diese URL kopieren und in deinem Browser öffnen:.
        /// </summary>
        public static string NewReleaseUrlToDownload {
            get {
                return ResourceManager.GetString("NewReleaseUrlToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bilder der Antworten herunterladen?.
        /// </summary>
        public static string OptionDownloadImages {
            get {
                return ResourceManager.GetString("OptionDownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für jede Antwort die Bilder in einen eigenen Ordner herunterladen?.
        /// </summary>
        public static string OptionDownloadImagesToOwnFolder {
            get {
                return ResourceManager.GetString("OptionDownloadImagesToOwnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für jede Gruppe die Beiträge in eigene Ordner herunterladen?.
        /// </summary>
        public static string OptionDownloadToOwnFolder {
            get {
                return ResourceManager.GetString("OptionDownloadToOwnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Namen der Gruppe am Anfang angeben?.
        /// </summary>
        public static string OptionIncludeGroup {
            get {
                return ResourceManager.GetString("OptionIncludeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch den Eigentümer der Gruppe angeben?.
        /// </summary>
        public static string OptionIncludeGroupAuthor {
            get {
                return ResourceManager.GetString("OptionIncludeGroupAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch angeben, wann die Gruppe erstellt wurde?.
        /// </summary>
        public static string OptionIncludeGroupPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludeGroupPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch die URL der Gruppe angeben?.
        /// </summary>
        public static string OptionIncludeGroupUrl {
            get {
                return ResourceManager.GetString("OptionIncludeGroupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Antworten mit ihren Bildern exportieren?.
        /// </summary>
        public static string OptionIncludeImages {
            get {
                return ResourceManager.GetString("OptionIncludeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Seitenzahl angeben?.
        /// </summary>
        public static string OptionIncludePageNumber {
            get {
                return ResourceManager.GetString("OptionIncludePageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Autor der Antworten angeben?.
        /// </summary>
        public static string OptionIncludePostAuthor {
            get {
                return ResourceManager.GetString("OptionIncludePostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nummer der Antwort angeben?.
        /// </summary>
        public static string OptionIncludePostNumber {
            get {
                return ResourceManager.GetString("OptionIncludePostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angeben, wann die Antwort gepostet wurde?.
        /// </summary>
        public static string OptionIncludePostPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludePostPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Namen des Beitrags am Anfang angeben?.
        /// </summary>
        public static string OptionIncludeThread {
            get {
                return ResourceManager.GetString("OptionIncludeThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch den Autor des Beitrags angeben?.
        /// </summary>
        public static string OptionIncludeThreadAuthor {
            get {
                return ResourceManager.GetString("OptionIncludeThreadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch angeben, wann der Beitrag erstellt wurde?.
        /// </summary>
        public static string OptionIncludeThreadPostedAt {
            get {
                return ResourceManager.GetString("OptionIncludeThreadPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auch die URL des Beitrags angeben?.
        /// </summary>
        public static string OptionIncludeThreadUrl {
            get {
                return ResourceManager.GetString("OptionIncludeThreadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Reihenfolge der Beiträge umkehren (von der neuesten zur ältesten statt von der ältesten zur neuesten)?.
        /// </summary>
        public static string OptionReserveOrder {
            get {
                return ResourceManager.GetString("OptionReserveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdefinierte Templates verwenden.
        /// </summary>
        public static string OptionUseCustomTemplates {
            get {
                return ResourceManager.GetString("OptionUseCustomTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AktuelleZahlAntworten].
        /// </summary>
        public static string PlaceholderCurrentPostNumber {
            get {
                return ResourceManager.GetString("PlaceholderCurrentPostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GruppeEigentümer].
        /// </summary>
        public static string PlaceholderGroupAuthor {
            get {
                return ResourceManager.GetString("PlaceholderGroupAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GruppeErstelltAm].
        /// </summary>
        public static string PlaceholderGroupPostedAt {
            get {
                return ResourceManager.GetString("PlaceholderGroupPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GruppeName].
        /// </summary>
        public static string PlaceholderGroupTitle {
            get {
                return ResourceManager.GetString("PlaceholderGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GruppeUrl].
        /// </summary>
        public static string PlaceholderGroupUrl {
            get {
                return ResourceManager.GetString("PlaceholderGroupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AntwortAutor].
        /// </summary>
        public static string PlaceholderPostAuthor {
            get {
                return ResourceManager.GetString("PlaceholderPostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AntwortGepostetAm].
        /// </summary>
        public static string PlaceholderPostPostedAt {
            get {
                return ResourceManager.GetString("PlaceholderPostPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Antworten].
        /// </summary>
        public static string PlaceholderPosts {
            get {
                return ResourceManager.GetString("PlaceholderPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AntwortText].
        /// </summary>
        public static string PlaceholderPostText {
            get {
                return ResourceManager.GetString("PlaceholderPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BeitragAutor].
        /// </summary>
        public static string PlaceholderThreadAuthor {
            get {
                return ResourceManager.GetString("PlaceholderThreadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BeitragErstelltAm].
        /// </summary>
        public static string PlaceholderThreadPostedAt {
            get {
                return ResourceManager.GetString("PlaceholderThreadPostedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BeitragName].
        /// </summary>
        public static string PlaceholderThreadTitle {
            get {
                return ResourceManager.GetString("PlaceholderThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BeitragUrl].
        /// </summary>
        public static string PlaceholderThreadUrl {
            get {
                return ResourceManager.GetString("PlaceholderThreadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GesamteZahlAntworten].
        /// </summary>
        public static string PlaceholderTotalPostNumber {
            get {
                return ResourceManager.GetString("PlaceholderTotalPostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen:.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit allen Platzhaltern.
        /// </summary>
        public static string ResetAllPlaceholders {
            get {
                return ResourceManager.GetString("ResetAllPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit aktuellen Platzhaltern.
        /// </summary>
        public static string ResetCurrentPlaceholders {
            get {
                return ResourceManager.GetString("ResetCurrentPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Deine Gruppen:.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gruppen auswählen.
        /// </summary>
        public static string SelectSelectGroups {
            get {
                return ResourceManager.GetString("SelectSelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gruppen und Beiträge auswählen.
        /// </summary>
        public static string SelectSelectGroupsThreads {
            get {
                return ResourceManager.GetString("SelectSelectGroupsThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beiträge auswählen.
        /// </summary>
        public static string SelectSelectThreads {
            get {
                return ResourceManager.GetString("SelectSelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Deine Beiträge:.
        /// </summary>
        public static string SelectThreads {
            get {
                return ResourceManager.GetString("SelectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Deine Beiträge von {0}:.
        /// </summary>
        public static string SelectThreadsOf {
            get {
                return ResourceManager.GetString("SelectThreadsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gruppen abwählen.
        /// </summary>
        public static string SelectUnselectGroups {
            get {
                return ResourceManager.GetString("SelectUnselectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gruppen und Beiträge abwählen.
        /// </summary>
        public static string SelectUnselectGroupsThreads {
            get {
                return ResourceManager.GetString("SelectUnselectGroupsThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beiträge abwählen.
        /// </summary>
        public static string SelectUnselectThreads {
            get {
                return ResourceManager.GetString("SelectUnselectThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export starten.
        /// </summary>
        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unter.
        /// </summary>
        public static string TemplateAt {
            get {
                return ResourceManager.GetString("TemplateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        public static string TemplateFrom {
            get {
                return ResourceManager.GetString("TemplateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild unter.
        /// </summary>
        public static string TemplateImageAt {
            get {
                return ResourceManager.GetString("TemplateImageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to am.
        /// </summary>
        public static string TemplateOn {
            get {
                return ResourceManager.GetString("TemplateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite.
        /// </summary>
        public static string TemplatePage {
            get {
                return ResourceManager.GetString("TemplatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Text-Datei Export verwendet die Text Templates. Der HTML-Datei und Word-Datei Export verwenden die HTML Templates. Die Head-Templates stehen für die Kopfzeile des Exports eines Beitrags und die Body-Templates für die Antworten des Beitrags. Beim Platzhalter.
        /// </summary>
        public static string TemplatesDetails1 {
            get {
                return ResourceManager.GetString("TemplatesDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bei den Head-Templates werden beim Exportieren die Body-Templates für die Antworten eingefügt.
        ///
        ///Die Standard-Templates basieren auf den aktuellen Export-Text-Optionen. Nur wenn eine Text-Option ausgewählt wurde, wird auch der Platzhalter im Standard-Template angezeigt..
        /// </summary>
        public static string TemplatesDetails2 {
            get {
                return ResourceManager.GetString("TemplatesDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body-Template für Html.
        /// </summary>
        public static string TemplatesHtmlBody {
            get {
                return ResourceManager.GetString("TemplatesHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head-Template für Html.
        /// </summary>
        public static string TemplatesHtmlHead {
            get {
                return ResourceManager.GetString("TemplatesHtmlHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional:.
        /// </summary>
        public static string TemplatesOptionalPlaceholders {
            get {
                return ResourceManager.GetString("TemplatesOptionalPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Platzhalter.
        /// </summary>
        public static string TemplatesPlaceholders {
            get {
                return ResourceManager.GetString("TemplatesPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erforderlich:.
        /// </summary>
        public static string TemplatesRequiredPlaceholders {
            get {
                return ResourceManager.GetString("TemplatesRequiredPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body-Template für Text.
        /// </summary>
        public static string TemplatesTextBody {
            get {
                return ResourceManager.GetString("TemplatesTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head-Template für Text.
        /// </summary>
        public static string TemplatesTextHead {
            get {
                return ResourceManager.GetString("TemplatesTextHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdefinierte Templates.
        /// </summary>
        public static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beitrag.
        /// </summary>
        public static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Export.
        /// </summary>
        public static string ToExport {
            get {
                return ResourceManager.GetString("ToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates updaten.
        /// </summary>
        public static string UpdateTemplates {
            get {
                return ResourceManager.GetString("UpdateTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die URL des Forums scheint nicht gültig zu sein!.
        /// </summary>
        public static string WarningInvalidBaseUrl {
            get {
                return ResourceManager.GetString("WarningInvalidBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib zuerst die URL des Forums ein!.
        /// </summary>
        public static string WarningMissingBaseUrl {
            get {
                return ResourceManager.GetString("WarningMissingBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle mindestens ein Export-Dateiformat aus!.
        /// </summary>
        public static string WarningMissingFileFormat {
            get {
                return ResourceManager.GetString("WarningMissingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle zuerst einen Export-Ordner aus!.
        /// </summary>
        public static string WarningMissingFolder {
            get {
                return ResourceManager.GetString("WarningMissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib zuerst dein Passwort ein!.
        /// </summary>
        public static string WarningMissingPassword {
            get {
                return ResourceManager.GetString("WarningMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib zuerst deinen Benutzernamen ein!.
        /// </summary>
        public static string WarningMissingUsername {
            get {
                return ResourceManager.GetString("WarningMissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du musst mindestens eine Gruppe und einen Beitrag auswählen!.
        /// </summary>
        public static string WarningNothingSelected {
            get {
                return ResourceManager.GetString("WarningNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten keine Beiträge für Gruppe {0} geladen werden! (Wenn das ein Fehler ist, kontaktiere mich bitte über den Feedback-Dialog.).
        /// </summary>
        public static string WarningNoThreadsFor {
            get {
                return ResourceManager.GetString("WarningNoThreadsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur eine Vorwarnung: Der Word-Export schlägt manchmal fehl, weil Bilder nicht hinzugefügt werden können. (Der Fehler tritt seltener auf, wenn man die Bilder der Antworten herunterlädt.) Meistens ist dieser Fehler nur vorübergehend. Wenn du es nach ein paar Minuten erneut versuchst, sollte es wahrscheinlich funktionieren..
        /// </summary>
        public static string WarningSelectedDocx {
            get {
                return ResourceManager.GetString("WarningSelectedDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle zuerst eine Gruppe aus..
        /// </summary>
        public static string WarningSelectGroupFirst {
            get {
                return ResourceManager.GetString("WarningSelectGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du konntest nicht eingeloggt werden! Bitte überprüfe deinen Benutzernamen und dein Passwort..
        /// </summary>
        public static string WarningWrongUsernamePassword {
            get {
                return ResourceManager.GetString("WarningWrongUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wäre super, falls du Sentry erlauben könntest, Fehler zu verfolgen! Darf Sentry Daten sammeln, wenn ein Fehler auftritt?.
        /// </summary>
        public static string WelcomeAllowSentryQuestion {
            get {
                return ResourceManager.GetString("WelcomeAllowSentryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur eine kleine Vorwarnung, bevor du loslegst: Das Programm befindet sich noch in der Entwicklungsphase. Es kann sein, dass du auf einige Fehler stößt und einige Funktionen sind noch in der Entwicklung. Vergewissere dich, dass du die aktuellste Version verwendest!
        ///
        ///Wenn du Hilfe benötigst, findest du auf den meisten Seiten oben einen &quot;Hilfe&quot;-Button, der die aktuelle Seite im Detail erklärt. Es gibt auch einen &quot;Feedback&quot;-Button für deine Ideen, Vorschläge und allgemeines Feedback, über das ich mich immer f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke, dass du den Post Exporter benutzt.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
